---
# ---
# Oncue Server Team Playbook
# ---

##### User Handling #####
- name: Groups | Create Admin Group
  group: name={{ item.name }} state=present
  with_items:
    - { name: 'imis_servers' }
  tags:
    - users

- name: Users | Setup user sudoers.d files
  template: src=sudoers.d-group.j2 dest=/etc/sudoers.d/{{ item.name }} mode=0440
  with_items:
    - { name: 'imis_servers' }
  tags: 
    - users

- name: Users | Create / Setup Users
  user: name={{ item.name }} state={{ item.state }} groups={{ item.groups }} shell=/bin/bash append=yes 
  with_items: user_accounts
  tags:
    - users

- name: Users | deploy keys for users
  authorized_key: user={{ item.name }} key="{{ lookup('file', item.name + '_id_rsa.pub') }}"
  with_items: user_accounts
  when: item.state == 'present'
  tags:
    - users
    - users_public_keys
