---
linux_isos:
    - { url: 'http://68.140.250.12/images/CentOS-6.3-x86_64-bin-DVD1.iso', path: '/images/CentOS-6.3-x86_64-bin-DVD1.iso', name: 'CentOS-6.3-x86_64', kopts: "", kopts_post: ""}
    - { url: 'http://68.140.250.12/images/CentOS-6.5-x86_64-bin-DVD1.iso', path: '/images/CentOS-6.5-x86_64-bin-DVD1.iso', name: 'CentOS-6.5-x86_64', kopts: "", kopts_post: ""}
    - { url: 'http://68.140.250.12/images/CentOS-6.6-x86_64-bin-DVD1.iso', path: '/images/CentOS-6.6-x86_64-bin-DVD1.iso', name: 'CentOS-6.6-x86_64', kopts: "", kopts_post: ""}
    - { url: 'http://68.140.250.12/images/CentOS-7.0-1406-x86_64-DVD.iso', path: '/images/CentOS-7.0-1406-x86_64-DVD.iso', name: 'CentOS-7.0-x86_64', kopts: "biosdevname=0 net.ifnames=0", kopts_post: "biosdevname=0 net.ifnames=0"}

cobbler_profiles:
    - { name: '6.3-1ru-generic-base', distro: 'CentOS-6.3-x86_64', kickstart: '/var/lib/cobbler/kickstarts/1ru-generic-base.ks' }
    - { name: '6.3-2ru-generic-base', distro: 'CentOS-6.3-x86_64', kickstart: '/var/lib/cobbler/kickstarts/2ru-generic-base.ks' }
    - { name: '6.5-1ru-generic-base', distro: 'CentOS-6.5-x86_64', kickstart: '/var/lib/cobbler/kickstarts/1ru-generic-base.ks' }
    - { name: '6.5-2ru-generic-base', distro: 'CentOS-6.5-x86_64', kickstart: '/var/lib/cobbler/kickstarts/2ru-generic-base.ks' }
    - { name: '7.0-1ru-generic-base', distro: 'CentOS-7.0-x86_64', kickstart: '/var/lib/cobbler/kickstarts/1ru-generic-base-7.0.ks' }
    - { name: '7.0-1ru-es', distro: 'CentOS-7.0-x86_64', kickstart: '/var/lib/cobbler/kickstarts/1ru-7.0-es.ks' }
    - { name: '7.0-2ru-ceph-osd-base', distro: 'CentOS-7.0-x86_64', kickstart: '/var/lib/cobbler/kickstarts/2ru-ceph-osd-base.ks' }

repos:
    - "epel"
    - "intelmedia"
    - "updates"

repo_sync:
    - { name: "CentOS-6.0-EPEL", arch: "x86_64" }
    - { name: "CentOS-6.0-Updates", arch: "x86_64" }
    - { name: "CentOS-7.0-Core", arch: "x86_64" }
    - { name: "CentOS-7.0-EPEL", arch: "x86_64" }
    - { name: "CentOS-7.0-Updates", arch: "x86_64" }
    - { name: "Ceph_RHEL6-x86_64", arch: "x86_64" }
    - { name: "Ceph_CentOS6_RH-x86_64", arch: "x86_64" }
    - { name: "Ceph_RHEL7-x86_64", arch: "x86_64" }
