---

  file: path={{ path_iso_image }} state=directory mode=0755

  name: Cobbler ISO Import | Mount ISOs
  shell: /usr/bin/mount -o loop /dev/cdrom {{ path_iso_image }} && touch /root/.mount_iso
  args:
   creates: /root/.mount_iso
  run_once: true
  ignore_errors: True

  name: Cobbler ISO Import | Import the DVDs into distros
  shell: /usr/bin/cobbler import --arch=x86_64 --path={{ path_iso_image }} --name={{ os_name }} && touch /root/.iso_import
  args:
   creates: /root/.iso_import
  run_once: true
  ignore_errors: True

  cobbler_profile:
      { name: '7.1-1ru-generic-base', distro: 'rhel-server-7.1-x86_64', kickstart: '/var/lib/cobbler/kickstarts/CentOS-7.ks' }

##### Welcome Banner

#-   motd_welome: '*******************\nWelcome to Unixolu\nAnsible Test\n*******************\n'
#    cobbler_ip: '172.16.0.20'
#    cobbler_name: 'testcob'
#    default_password_crypted: '$1$py9eJWQg$TkWHBVveK6AvYuXJtJAVw/'
#    subnet: '172.16.0.0'
#    netmask: '255.255.255.0'
#    option_domain_name_servers: '172.16.0.43'
#    option_subnet_mask: '255.255.255.0'
#    range_dynamic_bootp: "172.16.0.170 172.16.0.190"
#    dhcp_range: "172.16.0.170,172.16.0.190"
#    path_iso_image: '/mnt/iso'
#    os_name: 'CentOS-7'
#    manage_forward_zones: 'unixolu.com'
#    manage_reverse_zones: '172.16.0'
