---


###
# Cobbler Insstallation CentOS-7
#    - name: sample motd
#      copy:
#       dest: /etc/motd
#       content: "{{ motd_welome }}"

    - name: Install the latest epel repository for CentOS7....
      action: yum name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=installed

    - name: Cobbler Base | Cobbler Specific Package Install
      yum: pkg={{item}} state=installed 
      with_items:
      - cobbler
      - cobbler-web
      - dnsmasq
      - syslinux
      - pykickstart
      - fence-agents
      - xinetd
      - tftp
      tags: yum

    - name: System Services | Turn on required services
      service: name={{ item }} state=restarted enabled=yes
      with_items:
        - cobblerd
        - httpd
        - xinetd
      tags: services
 
    ##### Cobbler Configs #####
    - name: Setting Cobbler Root password for installed systems
      replace:
       dest: /etc/cobbler/settings
       regexp: 'default_password_crypted: "\$1\$mF86/UHC\$WvcIcX2t6crBz2onWxyac."'
       replace: 'default_password_crypted: "{{ default_password_crypted }}"'
    
    - name: Enable DHCP for cobbler
      replace:
       dest: /etc/cobbler/settings
       regexp: 'manage_dhcp: 0'
       replace: 'manage_dhcp: 1'
    
    - name: Enable DNS for cobbler
      replace:
       dest: /etc/cobbler/settings
       regexp: 'manage_dns: 0'
       replace: 'manage_dns: 1'
    
    - name: Enable PXE for cobbler
      replace:
       dest: /etc/cobbler/settings
       regexp: 'pxe_just_once: 0'
       replace: 'pxe_just_once: 1'
    
    - name: Setup next_server for cobbler
      replace:
       dest: /etc/cobbler/settings
       regexp: 'next_server: 127.0.0.1'
       replace: 'next_server: {{ cobbler_ip }}'
    
    - name: Setup server for cobbler
      replace:
       dest: /etc/cobbler/settings
       regexp: 'server: 127.0.0.1'
       replace: 'server: {{ cobbler_ip }}'
       backup: yes
#   
#    - name: Setup dns forward zones with cobbler
#      replace:
#       dest: /etc/cobbler/settings
#       regexp: 'manage_forward_zones: []'
#       replace: "manage_forward_zones: \['unixolu.com'\]"

#    - name: Setup dns reverse zones with cobbler
#      replace:
#       dest: /etc/cobbler/settings
#       regexp: 'manage_reverse_zones: []'
#       replace: "manage_reverse_zones: [{{ manage_reverse_zones }}]"
#       backup: yes

    - name: Setup dnsmasq for cobbler dns
      replace:
       dest: /etc/cobbler/modules.conf
       regexp: 'module = manage_bind'
       replace: 'module = manage_dnsmasq'
    
    - name: Setup dnsmasq for cobbler dhcp
      replace:
       dest: /etc/cobbler/modules.conf
       regexp: 'module = manage_isc'
       replace: 'module = manage_dnsmasq'
       backup: yes
    
    - name: Setting up dhcp server for cobbler
      replace:
       dest: /etc/cobbler/dhcp.template
       regexp: 'subnet 192.168.1.0 netmask 255.255.255.0'
       replace: 'subnet {{ subnet_ip_ranges }} netmask {{ option_subnet_mask }}'
    
    - name: Setting up dhcp server option router for cobbler
      replace:
       dest: /etc/cobbler/dhcp.template
       regexp: 'option routers             192.168.1.5'
       replace: 'option routers             {{ cobbler_ip }}'
    
    - name: Setting up dhcp server option dns for cobbler
      replace:
       dest: /etc/cobbler/dhcp.template
       regexp: 'option domain-name-servers 192.168.1.5'
       replace: 'option domain-name-servers {{ option_domain_name_servers }}'
    
    - name: Setting up dhcp server option netmask for cobbler
      replace:
       dest: /etc/cobbler/dhcp.template
       regexp: 'option subnet-mask         255.255.255.0'
       replace: 'option subnet-mask         {{ option_subnet_mask }}'
    
    - name: Setting up dhcp server range for cobbler
      replace:
       dest: /etc/cobbler/dhcp.template
       regexp: 'range dynamic-bootp        192.168.1.100 192.168.1.254'
       replace: 'range dynamic-bootp       {{ range_dynamic_bootp }}'
       backup: yes
    
    - name: Setting up dnsmasg for dhcp
      replace:
       dest: /etc/cobbler/dnsmasq.template
       regexp: 'dhcp-range=192.168.1.5,192.168.1.200'
       replace: 'dhcp-range={{ dhcp_range }}'
       backup: yes

    - name: Disable xinetd.d for tftp
      template: src=file/tftp.j2 dest=/etc/xinetd.d/tftp
    - name: Disable xinetd.d for rsync
      template: src=file/rsync.j2 dest=/etc/xinetd.d/rsync
    - name: Download network boot-loaders that are missing
      shell: /usr/bin/cobbler get-loaders && touch /root/.boot-loaders
      args:
       creates: /root/.boot-loaders
      run_once: true
      ignore_errors: True
#       shall: [ -f "/var/lib/cobbler/loaders/pxelinux.0" ] || cobbler get-loaders
#      command: '[ -f "/var/lib/cobbler/loaders/pxelinux.0" ] || { cobbler get-loaders;}'

    - name: running cobbler sync
      command: /usr/bin/cobbler sync
