---
- hosts: all
  sudo: yes
  gather_facts: yes

  tasks:

  - name: install ntp
    yum: name=ntp state=installed update_cache=yes
    when: ansible_os_family == "CentOS7"

  - name: start ntp
    service: name=ntpd state=started enabled=true
    when: ansible_os_family == "CentOS7"
